title: Venu Madhav Palugula
description: Infrastructure • Reliability • Distributed Systems
remote_theme: just-the-docs/just-the-docs

# Aux links for the upper right navigation
aux_links:
  "GitHub":
    - "https://github.com/venkube"
  "LinkedIn":
    - "https://linkedin.com/in/palugulavenumadhav"
  "Medium":
    - "https://medium.com/@venkube"

aux_links_new_tab: true

color_scheme: dark

logo: "/assets/images/profile.png"

permalink: pretty

plugins:
  - jekyll-remote-theme

header_pages:
  - about.md
  - projects.md
  - writing.md

author:
  name: Venu Madhav Palugula
  email: palugulavenumadhav@gmail.com
