title: Venu Madhav Palugula
description: Infrastructure • Reliability • Distributed Systems
remote_theme: remote_theme: "mmistakes/minimal-mistakes@4.19.2"
name: Venu Madhav Palugula
url: https://venkube.github.io/
logo: "/assets/images/screen_saver.jpeg"

minimal_mistakes_skin: "default"

navigation:
  main:
    - title: "About"
      url: /about/
    - title: "Projects"
      url: /projects/
    - title: "Writing"
      url: /writing/

logo: "/assets/images/screen_saver.jpeg"

plugins:
  - jekyll-remote-theme
  - jekyll-feed

header_pages:
  - about.md
  - projects.md
  - writing.md

author:
  name: "Venu Madhav"
  email: palugulavenumadhav@gmail.com
  avatar: "/assets/images/screen_saver.jpeg"
  bio: "Infrastructure • Reliability • Distributed Systems"
  location: "India"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/venkube"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/palugulavenumadhav"
    - label: "Medium"
      icon: "fab fa-medium"
      url: "https://medium.com/@venkube"

